-- ============================================================
-- clear-database.sql
-- Wipes all app data from the proof-reading-engine database.
-- Run in: Supabase Dashboard → SQL Editor → New query → Run
-- ============================================================
-- Table hierarchy (parent → child):
--   sessions
--     └── sections          (FK: session_id → sessions.id CASCADE)
--     └── chat_messages     (FK: session_id → sessions.id CASCADE)
--
-- sessions columns reset by this wipe:
--   review_score, review_report         (task-004)
--   tone_consistency_score, tone_report (task-005)
--   completeness_score, completeness_report (task-006)
--   citations_report                    (task-012)
--
-- sections columns reset by this wipe:
--   tone_label, tone_score              (task-005)
--   reformatted_text, reformat_type     (task-008)
-- ============================================================

-- Child tables first, then parent (CASCADE handles the rest)
TRUNCATE TABLE chat_messages, sections, sessions RESTART IDENTITY CASCADE;

-- ============================================================
-- Optional: wipe Supabase Auth users
-- WARNING: deletes all accounts and cannot be undone.
-- Uncomment only for a full environment reset.
-- ============================================================
-- DELETE FROM auth.mfa_factors;
-- DELETE FROM auth.refresh_tokens;
-- DELETE FROM auth.sessions;
-- DELETE FROM auth.users;
